name: 'Bitmaker Cloud Deploy'
description: 'Deploy Scrapy projects to Bitmaker Cloud (Estela)'
author: 'Kate'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  username:
    description: 'Bitmaker Cloud username'
    required: true
  password:
    description: 'Bitmaker Cloud password'
    required: true
  project-id:
    description: 'Project ID from Bitmaker Cloud'
    required: true
  host:
    description: 'Bitmaker Cloud API host'
    required: false
    default: 'https://api.cloud.bitmaker.dev'

outputs:
  status:
    description: 'Deployment status'

runs:
  using: 'docker'
  image: 'Dockerfile'
